In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
from sklearn.datasets import load_breast_cancer
df = load_breast_cancer()

In [4]:
x = pd.DataFrame(data=df.data, columns=df.feature_names)
x.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [5]:
x.shape

(569, 30)

In [6]:
x.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'],
      dtype='object')

In [7]:
x.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry      

In [8]:
y = df.target
y.shape

(569,)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.23,stratify=y)

In [10]:
x_train.shape

(438, 30)

In [11]:
y_test.shape

(131,)

In [14]:
q = x_train.loc[23]
np.array(q)

array([2.116e+01, 2.304e+01, 1.372e+02, 1.404e+03, 9.428e-02, 1.022e-01,
       1.097e-01, 8.632e-02, 1.769e-01, 5.278e-02, 6.917e-01, 1.127e+00,
       4.303e+00, 9.399e+01, 4.728e-03, 1.259e-02, 1.715e-02, 1.038e-02,
       1.083e-02, 1.987e-03, 2.917e+01, 3.559e+01, 1.880e+02, 2.615e+03,
       1.401e-01, 2.600e-01, 3.155e-01, 2.009e-01, 2.822e-01, 7.526e-02])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
x_train

array([[ 1.12209619,  0.2987397 ,  1.09773341, ...,  1.29073752,
         0.2488411 ,  0.05309375],
       [ 1.97548792,  0.96087967,  1.98755801, ...,  1.49346478,
         0.354754  , -0.29080246],
       [ 2.64952274,  0.613827  ,  2.54422553, ...,  1.86642105,
         1.09774907,  0.41276501],
       ...,
       [-0.91736539, -0.17389124, -0.90163077, ..., -0.54355735,
        -1.04939434, -0.35232518],
       [ 1.3014531 ,  0.20512681,  1.27907207, ...,  0.54172991,
        -0.90496765, -0.51585992],
       [-0.07554508,  0.05671613, -0.13030888, ..., -0.85260036,
        -0.62895221, -0.78403587]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
z = KNeighborsClassifier()
z.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
yp = z.predict(x_test)

In [ ]:
z.score(x_test, y_test)

0.9694656488549618

In [ ]:
from sklearn.ensemble import RandomForestClassifier
zr = RandomForestClassifier(n_estimators=100, random_state=10)
zr.fit(x_train, y_train)

RandomForestClassifier(random_state=10)

In [ ]:
ypr = zr.predict(x_test)
zr.score(x_test, y_test)

0.9465648854961832

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
za = AdaBoostClassifier(n_estimators=100, random_state=10)
za.fit(x_train, y_train)

AdaBoostClassifier(n_estimators=100, random_state=10)

In [ ]:
ypa = za.predict(x_test)
za.score(x_test, y_test)

0.9770992366412213

In [ ]:
from xgboost import XGBClassifier
zx = XGBClassifier(n_estimators=800, learning_rate=0.07)
zx.fit(x_train, y_train,
       early_stopping_rounds=5,
       eval_set=[(x_test, y_test)],
       verbose=False)

c:\ProgramData\Anaconda3\lib\site-packages\xgboost\sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.07, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=800,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [ ]:
ypx = zx.predict(x_test)
zx.score(x_test, y_test)

0.9923664122137404

In [ ]:
x_train[23]

array([-0.86240118,  0.70515665, -0.85524181, -0.78730682, -0.03554668,
       -0.41342157, -0.50653568, -0.67626942,  0.82793103,  0.41630041,
       -0.45122134,  0.52755452, -0.4236318 , -0.48276152, -1.16230706,
        0.30920137,  0.12015128, -0.2168578 ,  1.09546926,  0.36270978,
       -0.89287766,  0.39327095, -0.89027053, -0.78582317, -1.04650607,
       -0.48248379, -0.56389623, -0.77166421,  0.42375786, -0.19457463])

In [ ]:
za.predict([[-0.33146207, -0.70016767, -0.35476869, -0.41541143,  0.15189877,
       -0.28869714, -0.68459119, -0.63511225, -0.30581561, -0.10672736,
       -0.90671245, -0.55647388, -0.88878428, -0.61245854, -1.39085786,
       -0.68616505, -0.48370045, -0.68983679, -0.26306178, -0.6812681 ,
       -0.49219183, -0.41294271, -0.51538162, -0.52664093, -0.67786144,
       -0.34941902, -0.41930589, -0.45285758,  0.6048671 , -0.29340668]])[0]

1

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
r2s = []
rmse = []
mae = []

for i in (yp, ypr, ypa, ypx):
  r2s.append(r2_score(y_test, i))
  rmse.append(np.sqrt(mean_squared_error(y_test, i)))
  mae.append(mean_absolute_error(y_test, i))

In [ ]:
res = pd.DataFrame({'R2Score':r2s, 'RootMeanSquaredError':rmse, 'MeanAbsoluteError':mae}, index=['KNN','RandomForest', 'AdaBoost', 'XGBoost'])
res

R2Score  RootMeanSquaredError  MeanAbsoluteError
KNN           0.869587              0.174741           0.030534
RandomForest  0.771777              0.231160           0.053435
AdaBoost      0.902190              0.151330           0.022901
XGBoost       0.967397              0.087370           0.007634

In [ ]:
import pickle as pk

pk.dump(za, open('model.pkl', 'wb'))

In [ ]:
model = pk.load(open('model.pkl', 'rb'))
model.predict([[-0.33146207, -0.70016767, -0.35476869, -0.41541143,  0.15189877,
       -0.28869714, -0.68459119, -0.63511225, -0.30581561, -0.10672736,
       -0.90671245, -0.55647388, -0.88878428, -0.61245854, -1.39085786,
       -0.68616505, -0.48370045, -0.68983679, -0.26306178, -0.6812681 ,
       -0.49219183, -0.41294271, -0.51538162, -0.52664093, -0.67786144,
       -0.34941902, -0.41930589, -0.45285758,  0.6048671 , -0.29340668]])

array([1])